/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IAlgebraCustomPoolEntryPointInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "afterCreatePoolHook"
      | "beforeCreatePoolHook"
      | "createCustomPool"
      | "factory"
      | "setFee"
      | "setPlugin"
      | "setPluginConfig"
      | "setTickSpacing"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "afterCreatePoolHook",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeCreatePoolHook",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createCustomPool",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlugin",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPluginConfig",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTickSpacing",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "afterCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCustomPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPlugin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPluginConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTickSpacing",
    data: BytesLike
  ): Result;
}

export interface IAlgebraCustomPoolEntryPoint extends BaseContract {
  connect(runner?: ContractRunner | null): IAlgebraCustomPoolEntryPoint;
  waitForDeployment(): Promise<this>;

  interface: IAlgebraCustomPoolEntryPointInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  afterCreatePoolHook: TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  beforeCreatePoolHook: TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  createCustomPool: TypedContractMethod<
    [
      deployer: AddressLike,
      creator: AddressLike,
      tokenA: AddressLike,
      tokenB: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  setFee: TypedContractMethod<
    [pool: AddressLike, newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlugin: TypedContractMethod<
    [pool: AddressLike, newPluginAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPluginConfig: TypedContractMethod<
    [pool: AddressLike, newConfig: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTickSpacing: TypedContractMethod<
    [pool: AddressLike, newTickSpacing: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "afterCreatePoolHook"
  ): TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeCreatePoolHook"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCustomPool"
  ): TypedContractMethod<
    [
      deployer: AddressLike,
      creator: AddressLike,
      tokenA: AddressLike,
      tokenB: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<
    [pool: AddressLike, newFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlugin"
  ): TypedContractMethod<
    [pool: AddressLike, newPluginAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPluginConfig"
  ): TypedContractMethod<
    [pool: AddressLike, newConfig: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTickSpacing"
  ): TypedContractMethod<
    [pool: AddressLike, newTickSpacing: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
