/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LPPluginInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALGEBRA_BASE_PLUGIN_MANAGER"
      | "afterFlash"
      | "afterInitialize"
      | "afterModifyPosition"
      | "afterSwap"
      | "beforeFlash"
      | "beforeInitialize"
      | "beforeModifyPosition"
      | "beforeSwap"
      | "callback"
      | "collectPluginFee"
      | "convertToken0ToToken1"
      | "defaultPluginConfig"
      | "handlePluginFee"
      | "lpTokenByTicks"
      | "onERC721Received"
      | "pluginFeeRate"
      | "pool"
      | "positionValue"
      | "setPluginFeeRate"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FeeRateUpdated" | "TokenCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ALGEBRA_BASE_PLUGIN_MANAGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterFlash",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterInitialize",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "afterModifyPosition",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterSwap",
    values: [
      AddressLike,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeFlash",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeInitialize",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeModifyPosition",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeSwap",
    values: [
      AddressLike,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "callback", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collectPluginFee",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToken0ToToken1",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPluginConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handlePluginFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpTokenByTicks",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pluginFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionValue",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPluginFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ALGEBRA_BASE_PLUGIN_MANAGER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "afterFlash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "afterInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterModifyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "afterSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beforeFlash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeModifyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "beforeSwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callback", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectPluginFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToken0ToToken1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPluginConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handlePluginFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpTokenByTicks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pluginFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPluginFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FeeRateUpdatedEvent {
  export type InputTuple = [newFeeRate: BigNumberish];
  export type OutputTuple = [newFeeRate: bigint];
  export interface OutputObject {
    newFeeRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    addr: AddressLike
  ];
  export type OutputTuple = [
    tickLower: bigint,
    tickUpper: bigint,
    addr: string
  ];
  export interface OutputObject {
    tickLower: bigint;
    tickUpper: bigint;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LPPlugin extends BaseContract {
  connect(runner?: ContractRunner | null): LPPlugin;
  waitForDeployment(): Promise<this>;

  interface: LPPluginInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALGEBRA_BASE_PLUGIN_MANAGER: TypedContractMethod<[], [string], "view">;

  afterFlash: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  afterInitialize: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "nonpayable"
  >;

  afterModifyPosition: TypedContractMethod<
    [
      arg0: AddressLike,
      owner: AddressLike,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      deltaL: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  afterSwap: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: boolean,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeFlash: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeInitialize: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "nonpayable"
  >;

  beforeModifyPosition: TypedContractMethod<
    [
      arg0: AddressLike,
      owner: AddressLike,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      deltaL: BigNumberish,
      arg5: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;

  beforeSwap: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: boolean,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: boolean,
      arg6: BytesLike
    ],
    [[string, bigint, bigint]],
    "nonpayable"
  >;

  callback: TypedContractMethod<[], [string], "view">;

  collectPluginFee: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  convertToken0ToToken1: TypedContractMethod<
    [amount0: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  defaultPluginConfig: TypedContractMethod<[], [bigint], "view">;

  handlePluginFee: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  lpTokenByTicks: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  onERC721Received: TypedContractMethod<
    [
      arg0: AddressLike,
      from: AddressLike,
      tokenId: BigNumberish,
      arg3: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  pluginFeeRate: TypedContractMethod<[], [bigint], "view">;

  pool: TypedContractMethod<[], [string], "view">;

  positionValue: TypedContractMethod<
    [tickLower: BigNumberish, tickUpper: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  setPluginFeeRate: TypedContractMethod<
    [newFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [
      recipient: AddressLike,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      lpTokensToBurn: BigNumberish
    ],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALGEBRA_BASE_PLUGIN_MANAGER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "afterFlash"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterInitialize"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterModifyPosition"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      owner: AddressLike,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      deltaL: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterSwap"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: boolean,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      arg7: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeFlash"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeInitialize"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeModifyPosition"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      owner: AddressLike,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      deltaL: BigNumberish,
      arg5: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeSwap"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: boolean,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: boolean,
      arg6: BytesLike
    ],
    [[string, bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callback"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collectPluginFee"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "convertToken0ToToken1"
  ): TypedContractMethod<
    [amount0: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "defaultPluginConfig"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "handlePluginFee"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpTokenByTicks"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      from: AddressLike,
      tokenId: BigNumberish,
      arg3: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pluginFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionValue"
  ): TypedContractMethod<
    [tickLower: BigNumberish, tickUpper: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setPluginFeeRate"
  ): TypedContractMethod<[newFeeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      lpTokensToBurn: BigNumberish
    ],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;

  getEvent(
    key: "FeeRateUpdated"
  ): TypedContractEvent<
    FeeRateUpdatedEvent.InputTuple,
    FeeRateUpdatedEvent.OutputTuple,
    FeeRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;

  filters: {
    "FeeRateUpdated(uint24)": TypedContractEvent<
      FeeRateUpdatedEvent.InputTuple,
      FeeRateUpdatedEvent.OutputTuple,
      FeeRateUpdatedEvent.OutputObject
    >;
    FeeRateUpdated: TypedContractEvent<
      FeeRateUpdatedEvent.InputTuple,
      FeeRateUpdatedEvent.OutputTuple,
      FeeRateUpdatedEvent.OutputObject
    >;

    "TokenCreated(int24,int24,address)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
  };
}
