/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LPPluginFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WNativeToken"
      | "afterCreatePoolHook"
      | "beforeCreatePoolHook"
      | "collectFee"
      | "createCustomPool"
      | "deploy"
      | "entryPoint"
      | "lpTokenFactory"
      | "owner"
      | "renounceOwnership"
      | "setFee"
      | "setPlugin"
      | "setPluginConfig"
      | "setPluginFeeRate"
      | "setTickSpacing"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "PluginDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "WNativeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterCreatePoolHook",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeCreatePoolHook",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFee",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCustomPool",
    values: [AddressLike, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "deploy", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpTokenFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlugin",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPluginConfig",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPluginFeeRate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTickSpacing",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "WNativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "collectFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCustomPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPlugin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPluginConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPluginFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTickSpacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PluginDeployedEvent {
  export type InputTuple = [
    pool: AddressLike,
    plugin: AddressLike,
    deployer: AddressLike
  ];
  export type OutputTuple = [pool: string, plugin: string, deployer: string];
  export interface OutputObject {
    pool: string;
    plugin: string;
    deployer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LPPluginFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LPPluginFactory;
  waitForDeployment(): Promise<this>;

  interface: LPPluginFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WNativeToken: TypedContractMethod<[], [string], "view">;

  afterCreatePoolHook: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [void],
    "view"
  >;

  beforeCreatePoolHook: TypedContractMethod<
    [
      pool: AddressLike,
      arg1: AddressLike,
      arg2: AddressLike,
      arg3: AddressLike,
      arg4: AddressLike,
      arg5: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  collectFee: TypedContractMethod<
    [
      plugin: AddressLike,
      token: AddressLike,
      maxAmount: BigNumberish,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  createCustomPool: TypedContractMethod<
    [
      creator: AddressLike,
      tokenA: AddressLike,
      tokenB: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  deploy: TypedContractMethod<[pool: AddressLike], [string], "nonpayable">;

  entryPoint: TypedContractMethod<[], [string], "view">;

  lpTokenFactory: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFee: TypedContractMethod<
    [pool: AddressLike, newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlugin: TypedContractMethod<
    [pool: AddressLike, newPluginAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPluginConfig: TypedContractMethod<
    [pool: AddressLike, newConfig: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPluginFeeRate: TypedContractMethod<
    [plugin: AddressLike, newFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTickSpacing: TypedContractMethod<
    [pool: AddressLike, newTickSpacing: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WNativeToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "afterCreatePoolHook"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "beforeCreatePoolHook"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      arg1: AddressLike,
      arg2: AddressLike,
      arg3: AddressLike,
      arg4: AddressLike,
      arg5: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collectFee"
  ): TypedContractMethod<
    [
      plugin: AddressLike,
      token: AddressLike,
      maxAmount: BigNumberish,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCustomPool"
  ): TypedContractMethod<
    [
      creator: AddressLike,
      tokenA: AddressLike,
      tokenB: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deploy"
  ): TypedContractMethod<[pool: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lpTokenFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<
    [pool: AddressLike, newFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlugin"
  ): TypedContractMethod<
    [pool: AddressLike, newPluginAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPluginConfig"
  ): TypedContractMethod<
    [pool: AddressLike, newConfig: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPluginFeeRate"
  ): TypedContractMethod<
    [plugin: AddressLike, newFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTickSpacing"
  ): TypedContractMethod<
    [pool: AddressLike, newTickSpacing: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PluginDeployed"
  ): TypedContractEvent<
    PluginDeployedEvent.InputTuple,
    PluginDeployedEvent.OutputTuple,
    PluginDeployedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PluginDeployed(address,address,address)": TypedContractEvent<
      PluginDeployedEvent.InputTuple,
      PluginDeployedEvent.OutputTuple,
      PluginDeployedEvent.OutputObject
    >;
    PluginDeployed: TypedContractEvent<
      PluginDeployedEvent.InputTuple,
      PluginDeployedEvent.OutputTuple,
      PluginDeployedEvent.OutputObject
    >;
  };
}
