/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IAlgebraFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CUSTOM_POOL_DEPLOYER"
      | "POOLS_ADMINISTRATOR_ROLE"
      | "POOL_INIT_CODE_HASH"
      | "computeCustomPoolAddress"
      | "computePoolAddress"
      | "createCustomPool"
      | "createPool"
      | "customPoolByPair"
      | "defaultCommunityFee"
      | "defaultConfigurationForPool"
      | "defaultFee"
      | "defaultPluginFactory"
      | "defaultTickspacing"
      | "hasRoleOrOwner"
      | "owner"
      | "poolByPair"
      | "poolDeployer"
      | "renounceOwnershipStartTimestamp"
      | "setDefaultCommunityFee"
      | "setDefaultFee"
      | "setDefaultPluginFactory"
      | "setDefaultTickspacing"
      | "setVaultFactory"
      | "startRenounceOwnership"
      | "stopRenounceOwnership"
      | "vaultFactory"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CustomPool"
      | "DefaultCommunityFee"
      | "DefaultFee"
      | "DefaultPluginFactory"
      | "DefaultTickspacing"
      | "Pool"
      | "RenounceOwnershipFinish"
      | "RenounceOwnershipStart"
      | "RenounceOwnershipStop"
      | "VaultFactory"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CUSTOM_POOL_DEPLOYER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOLS_ADMINISTRATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_INIT_CODE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeCustomPoolAddress",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computePoolAddress",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCustomPool",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "customPoolByPair",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultCommunityFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultConfigurationForPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPluginFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTickspacing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRoleOrOwner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolByPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnershipStartTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultCommunityFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPluginFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTickspacing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startRenounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stopRenounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaultFactory",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "CUSTOM_POOL_DEPLOYER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOLS_ADMINISTRATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_INIT_CODE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeCustomPoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computePoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCustomPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "customPoolByPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultCommunityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultConfigurationForPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "defaultFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultPluginFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTickspacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRoleOrOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolByPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnershipStartTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultCommunityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPluginFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTickspacing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startRenounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopRenounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultFactory",
    data: BytesLike
  ): Result;
}

export namespace CustomPoolEvent {
  export type InputTuple = [
    deployer: AddressLike,
    token0: AddressLike,
    token1: AddressLike,
    pool: AddressLike
  ];
  export type OutputTuple = [
    deployer: string,
    token0: string,
    token1: string,
    pool: string
  ];
  export interface OutputObject {
    deployer: string;
    token0: string;
    token1: string;
    pool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultCommunityFeeEvent {
  export type InputTuple = [newDefaultCommunityFee: BigNumberish];
  export type OutputTuple = [newDefaultCommunityFee: bigint];
  export interface OutputObject {
    newDefaultCommunityFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultFeeEvent {
  export type InputTuple = [newDefaultFee: BigNumberish];
  export type OutputTuple = [newDefaultFee: bigint];
  export interface OutputObject {
    newDefaultFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultPluginFactoryEvent {
  export type InputTuple = [defaultPluginFactoryAddress: AddressLike];
  export type OutputTuple = [defaultPluginFactoryAddress: string];
  export interface OutputObject {
    defaultPluginFactoryAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultTickspacingEvent {
  export type InputTuple = [newDefaultTickspacing: BigNumberish];
  export type OutputTuple = [newDefaultTickspacing: bigint];
  export interface OutputObject {
    newDefaultTickspacing: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolEvent {
  export type InputTuple = [
    token0: AddressLike,
    token1: AddressLike,
    pool: AddressLike
  ];
  export type OutputTuple = [token0: string, token1: string, pool: string];
  export interface OutputObject {
    token0: string;
    token1: string;
    pool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenounceOwnershipFinishEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenounceOwnershipStartEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    finishTimestamp: BigNumberish
  ];
  export type OutputTuple = [timestamp: bigint, finishTimestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
    finishTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenounceOwnershipStopEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultFactoryEvent {
  export type InputTuple = [newVaultFactory: AddressLike];
  export type OutputTuple = [newVaultFactory: string];
  export interface OutputObject {
    newVaultFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAlgebraFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IAlgebraFactory;
  waitForDeployment(): Promise<this>;

  interface: IAlgebraFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CUSTOM_POOL_DEPLOYER: TypedContractMethod<[], [string], "view">;

  POOLS_ADMINISTRATOR_ROLE: TypedContractMethod<[], [string], "view">;

  POOL_INIT_CODE_HASH: TypedContractMethod<[], [string], "view">;

  computeCustomPoolAddress: TypedContractMethod<
    [customDeployer: AddressLike, token0: AddressLike, token1: AddressLike],
    [string],
    "view"
  >;

  computePoolAddress: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [string],
    "view"
  >;

  createCustomPool: TypedContractMethod<
    [
      deployer: AddressLike,
      creator: AddressLike,
      tokenA: AddressLike,
      tokenB: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  createPool: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, data: BytesLike],
    [string],
    "nonpayable"
  >;

  customPoolByPair: TypedContractMethod<
    [customDeployer: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;

  defaultCommunityFee: TypedContractMethod<[], [bigint], "view">;

  defaultConfigurationForPool: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        communityFee: bigint;
        tickSpacing: bigint;
        fee: bigint;
      }
    ],
    "view"
  >;

  defaultFee: TypedContractMethod<[], [bigint], "view">;

  defaultPluginFactory: TypedContractMethod<[], [string], "view">;

  defaultTickspacing: TypedContractMethod<[], [bigint], "view">;

  hasRoleOrOwner: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  poolByPair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;

  poolDeployer: TypedContractMethod<[], [string], "view">;

  renounceOwnershipStartTimestamp: TypedContractMethod<[], [bigint], "view">;

  setDefaultCommunityFee: TypedContractMethod<
    [newDefaultCommunityFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultFee: TypedContractMethod<
    [newDefaultFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultPluginFactory: TypedContractMethod<
    [newDefaultPluginFactory: AddressLike],
    [void],
    "nonpayable"
  >;

  setDefaultTickspacing: TypedContractMethod<
    [newDefaultTickspacing: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVaultFactory: TypedContractMethod<
    [newVaultFactory: AddressLike],
    [void],
    "nonpayable"
  >;

  startRenounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stopRenounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  vaultFactory: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CUSTOM_POOL_DEPLOYER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POOLS_ADMINISTRATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POOL_INIT_CODE_HASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "computeCustomPoolAddress"
  ): TypedContractMethod<
    [customDeployer: AddressLike, token0: AddressLike, token1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "computePoolAddress"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCustomPool"
  ): TypedContractMethod<
    [
      deployer: AddressLike,
      creator: AddressLike,
      tokenA: AddressLike,
      tokenB: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, data: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "customPoolByPair"
  ): TypedContractMethod<
    [customDeployer: AddressLike, tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "defaultCommunityFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultConfigurationForPool"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        communityFee: bigint;
        tickSpacing: bigint;
        fee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "defaultFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultPluginFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultTickspacing"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRoleOrOwner"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolByPair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolDeployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnershipStartTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setDefaultCommunityFee"
  ): TypedContractMethod<
    [newDefaultCommunityFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultFee"
  ): TypedContractMethod<[newDefaultFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultPluginFactory"
  ): TypedContractMethod<
    [newDefaultPluginFactory: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultTickspacing"
  ): TypedContractMethod<
    [newDefaultTickspacing: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVaultFactory"
  ): TypedContractMethod<[newVaultFactory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startRenounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stopRenounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultFactory"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CustomPool"
  ): TypedContractEvent<
    CustomPoolEvent.InputTuple,
    CustomPoolEvent.OutputTuple,
    CustomPoolEvent.OutputObject
  >;
  getEvent(
    key: "DefaultCommunityFee"
  ): TypedContractEvent<
    DefaultCommunityFeeEvent.InputTuple,
    DefaultCommunityFeeEvent.OutputTuple,
    DefaultCommunityFeeEvent.OutputObject
  >;
  getEvent(
    key: "DefaultFee"
  ): TypedContractEvent<
    DefaultFeeEvent.InputTuple,
    DefaultFeeEvent.OutputTuple,
    DefaultFeeEvent.OutputObject
  >;
  getEvent(
    key: "DefaultPluginFactory"
  ): TypedContractEvent<
    DefaultPluginFactoryEvent.InputTuple,
    DefaultPluginFactoryEvent.OutputTuple,
    DefaultPluginFactoryEvent.OutputObject
  >;
  getEvent(
    key: "DefaultTickspacing"
  ): TypedContractEvent<
    DefaultTickspacingEvent.InputTuple,
    DefaultTickspacingEvent.OutputTuple,
    DefaultTickspacingEvent.OutputObject
  >;
  getEvent(
    key: "Pool"
  ): TypedContractEvent<
    PoolEvent.InputTuple,
    PoolEvent.OutputTuple,
    PoolEvent.OutputObject
  >;
  getEvent(
    key: "RenounceOwnershipFinish"
  ): TypedContractEvent<
    RenounceOwnershipFinishEvent.InputTuple,
    RenounceOwnershipFinishEvent.OutputTuple,
    RenounceOwnershipFinishEvent.OutputObject
  >;
  getEvent(
    key: "RenounceOwnershipStart"
  ): TypedContractEvent<
    RenounceOwnershipStartEvent.InputTuple,
    RenounceOwnershipStartEvent.OutputTuple,
    RenounceOwnershipStartEvent.OutputObject
  >;
  getEvent(
    key: "RenounceOwnershipStop"
  ): TypedContractEvent<
    RenounceOwnershipStopEvent.InputTuple,
    RenounceOwnershipStopEvent.OutputTuple,
    RenounceOwnershipStopEvent.OutputObject
  >;
  getEvent(
    key: "VaultFactory"
  ): TypedContractEvent<
    VaultFactoryEvent.InputTuple,
    VaultFactoryEvent.OutputTuple,
    VaultFactoryEvent.OutputObject
  >;

  filters: {
    "CustomPool(address,address,address,address)": TypedContractEvent<
      CustomPoolEvent.InputTuple,
      CustomPoolEvent.OutputTuple,
      CustomPoolEvent.OutputObject
    >;
    CustomPool: TypedContractEvent<
      CustomPoolEvent.InputTuple,
      CustomPoolEvent.OutputTuple,
      CustomPoolEvent.OutputObject
    >;

    "DefaultCommunityFee(uint16)": TypedContractEvent<
      DefaultCommunityFeeEvent.InputTuple,
      DefaultCommunityFeeEvent.OutputTuple,
      DefaultCommunityFeeEvent.OutputObject
    >;
    DefaultCommunityFee: TypedContractEvent<
      DefaultCommunityFeeEvent.InputTuple,
      DefaultCommunityFeeEvent.OutputTuple,
      DefaultCommunityFeeEvent.OutputObject
    >;

    "DefaultFee(uint16)": TypedContractEvent<
      DefaultFeeEvent.InputTuple,
      DefaultFeeEvent.OutputTuple,
      DefaultFeeEvent.OutputObject
    >;
    DefaultFee: TypedContractEvent<
      DefaultFeeEvent.InputTuple,
      DefaultFeeEvent.OutputTuple,
      DefaultFeeEvent.OutputObject
    >;

    "DefaultPluginFactory(address)": TypedContractEvent<
      DefaultPluginFactoryEvent.InputTuple,
      DefaultPluginFactoryEvent.OutputTuple,
      DefaultPluginFactoryEvent.OutputObject
    >;
    DefaultPluginFactory: TypedContractEvent<
      DefaultPluginFactoryEvent.InputTuple,
      DefaultPluginFactoryEvent.OutputTuple,
      DefaultPluginFactoryEvent.OutputObject
    >;

    "DefaultTickspacing(int24)": TypedContractEvent<
      DefaultTickspacingEvent.InputTuple,
      DefaultTickspacingEvent.OutputTuple,
      DefaultTickspacingEvent.OutputObject
    >;
    DefaultTickspacing: TypedContractEvent<
      DefaultTickspacingEvent.InputTuple,
      DefaultTickspacingEvent.OutputTuple,
      DefaultTickspacingEvent.OutputObject
    >;

    "Pool(address,address,address)": TypedContractEvent<
      PoolEvent.InputTuple,
      PoolEvent.OutputTuple,
      PoolEvent.OutputObject
    >;
    Pool: TypedContractEvent<
      PoolEvent.InputTuple,
      PoolEvent.OutputTuple,
      PoolEvent.OutputObject
    >;

    "RenounceOwnershipFinish(uint256)": TypedContractEvent<
      RenounceOwnershipFinishEvent.InputTuple,
      RenounceOwnershipFinishEvent.OutputTuple,
      RenounceOwnershipFinishEvent.OutputObject
    >;
    RenounceOwnershipFinish: TypedContractEvent<
      RenounceOwnershipFinishEvent.InputTuple,
      RenounceOwnershipFinishEvent.OutputTuple,
      RenounceOwnershipFinishEvent.OutputObject
    >;

    "RenounceOwnershipStart(uint256,uint256)": TypedContractEvent<
      RenounceOwnershipStartEvent.InputTuple,
      RenounceOwnershipStartEvent.OutputTuple,
      RenounceOwnershipStartEvent.OutputObject
    >;
    RenounceOwnershipStart: TypedContractEvent<
      RenounceOwnershipStartEvent.InputTuple,
      RenounceOwnershipStartEvent.OutputTuple,
      RenounceOwnershipStartEvent.OutputObject
    >;

    "RenounceOwnershipStop(uint256)": TypedContractEvent<
      RenounceOwnershipStopEvent.InputTuple,
      RenounceOwnershipStopEvent.OutputTuple,
      RenounceOwnershipStopEvent.OutputObject
    >;
    RenounceOwnershipStop: TypedContractEvent<
      RenounceOwnershipStopEvent.InputTuple,
      RenounceOwnershipStopEvent.OutputTuple,
      RenounceOwnershipStopEvent.OutputObject
    >;

    "VaultFactory(address)": TypedContractEvent<
      VaultFactoryEvent.InputTuple,
      VaultFactoryEvent.OutputTuple,
      VaultFactoryEvent.OutputObject
    >;
    VaultFactory: TypedContractEvent<
      VaultFactoryEvent.InputTuple,
      VaultFactoryEvent.OutputTuple,
      VaultFactoryEvent.OutputObject
    >;
  };
}
