/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IAlgebraPluginInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "afterFlash"
      | "afterInitialize"
      | "afterModifyPosition"
      | "afterSwap"
      | "beforeFlash"
      | "beforeInitialize"
      | "beforeModifyPosition"
      | "beforeSwap"
      | "defaultPluginConfig"
      | "handlePluginFee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "afterFlash",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterInitialize",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "afterModifyPosition",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterSwap",
    values: [
      AddressLike,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeFlash",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeInitialize",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeModifyPosition",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeSwap",
    values: [
      AddressLike,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPluginConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handlePluginFee",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "afterFlash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "afterInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterModifyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "afterSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beforeFlash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeModifyPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "beforeSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultPluginConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handlePluginFee",
    data: BytesLike
  ): Result;
}

export interface IAlgebraPlugin extends BaseContract {
  connect(runner?: ContractRunner | null): IAlgebraPlugin;
  waitForDeployment(): Promise<this>;

  interface: IAlgebraPluginInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  afterFlash: TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      paid0: BigNumberish,
      paid1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  afterInitialize: TypedContractMethod<
    [sender: AddressLike, sqrtPriceX96: BigNumberish, tick: BigNumberish],
    [string],
    "nonpayable"
  >;

  afterModifyPosition: TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      desiredLiquidityDelta: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  afterSwap: TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      zeroToOne: boolean,
      amountRequired: BigNumberish,
      limitSqrtPrice: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeFlash: TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeInitialize: TypedContractMethod<
    [sender: AddressLike, sqrtPriceX96: BigNumberish],
    [string],
    "nonpayable"
  >;

  beforeModifyPosition: TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      desiredLiquidityDelta: BigNumberish,
      data: BytesLike
    ],
    [[string, bigint] & { selector: string; pluginFee: bigint }],
    "nonpayable"
  >;

  beforeSwap: TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      zeroToOne: boolean,
      amountRequired: BigNumberish,
      limitSqrtPrice: BigNumberish,
      withPaymentInAdvance: boolean,
      data: BytesLike
    ],
    [
      [string, bigint, bigint] & {
        selector: string;
        feeOverride: bigint;
        pluginFee: bigint;
      }
    ],
    "nonpayable"
  >;

  defaultPluginConfig: TypedContractMethod<[], [bigint], "view">;

  handlePluginFee: TypedContractMethod<
    [pluginFee0: BigNumberish, pluginFee1: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "afterFlash"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      paid0: BigNumberish,
      paid1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterInitialize"
  ): TypedContractMethod<
    [sender: AddressLike, sqrtPriceX96: BigNumberish, tick: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterModifyPosition"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      desiredLiquidityDelta: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterSwap"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      zeroToOne: boolean,
      amountRequired: BigNumberish,
      limitSqrtPrice: BigNumberish,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeFlash"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      amount0: BigNumberish,
      amount1: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeInitialize"
  ): TypedContractMethod<
    [sender: AddressLike, sqrtPriceX96: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeModifyPosition"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      bottomTick: BigNumberish,
      topTick: BigNumberish,
      desiredLiquidityDelta: BigNumberish,
      data: BytesLike
    ],
    [[string, bigint] & { selector: string; pluginFee: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeSwap"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      recipient: AddressLike,
      zeroToOne: boolean,
      amountRequired: BigNumberish,
      limitSqrtPrice: BigNumberish,
      withPaymentInAdvance: boolean,
      data: BytesLike
    ],
    [
      [string, bigint, bigint] & {
        selector: string;
        feeOverride: bigint;
        pluginFee: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultPluginConfig"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "handlePluginFee"
  ): TypedContractMethod<
    [pluginFee0: BigNumberish, pluginFee1: BigNumberish],
    [string],
    "nonpayable"
  >;

  filters: {};
}
