/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IAlgebraPluginFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "afterCreatePoolHook" | "beforeCreatePoolHook"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "afterCreatePoolHook",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeCreatePoolHook",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "afterCreatePoolHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeCreatePoolHook",
    data: BytesLike
  ): Result;
}

export interface IAlgebraPluginFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IAlgebraPluginFactory;
  waitForDeployment(): Promise<this>;

  interface: IAlgebraPluginFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  afterCreatePoolHook: TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  beforeCreatePoolHook: TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "afterCreatePoolHook"
  ): TypedContractMethod<
    [plugin: AddressLike, pool: AddressLike, deployer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeCreatePoolHook"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      creator: AddressLike,
      deployer: AddressLike,
      token0: AddressLike,
      token1: AddressLike,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
