/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAlgebraPlugin } from "./IAlgebraPlugin";
export type { IAlgebraPluginFactory } from "./IAlgebraPluginFactory";
