/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILPPluginFactory,
  ILPPluginFactoryInterface,
} from "../../../contracts/interfaces/ILPPluginFactory";

const _abi = [
  {
    inputs: [],
    name: "WNativeToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "plugin",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lpTokenFactory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILPPluginFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ILPPluginFactoryInterface {
    return new Interface(_abi) as ILPPluginFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILPPluginFactory {
    return new Contract(address, _abi, runner) as unknown as ILPPluginFactory;
  }
}
