/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILPTokenFactory,
  ILPTokenFactoryInterface,
} from "../../../contracts/interfaces/ILPTokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILPTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ILPTokenFactoryInterface {
    return new Interface(_abi) as ILPTokenFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILPTokenFactory {
    return new Contract(address, _abi, runner) as unknown as ILPTokenFactory;
  }
}
