/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAbstractPlugin } from "./IAbstractPlugin";
export type { ICustomPluginFactory } from "./ICustomPluginFactory";
