/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAlgebraVaultFactory,
  IAlgebraVaultFactoryInterface,
} from "../../../../../../@cryptoalgebra/integral-core/contracts/interfaces/vault/IAlgebraVaultFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "address",
        name: "deployer",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
    ],
    name: "createVaultForPool",
    outputs: [
      {
        internalType: "address",
        name: "communityFeeVault",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "getVaultForPool",
    outputs: [
      {
        internalType: "address",
        name: "communityFeeVault",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAlgebraVaultFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IAlgebraVaultFactoryInterface {
    return new Interface(_abi) as IAlgebraVaultFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAlgebraVaultFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAlgebraVaultFactory;
  }
}
