name: unit-test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat unit test
    env:
      ALCHEMY_URL: ${{ secrets.ALCHEMY_URL }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Compile contracts
      run: npx hardhat clean && npx hardhat compile
    - name: Run tests
      run: npx hardhat test ./test/invariants/*