/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAbstractPlugin__factory } from "./IAbstractPlugin__factory";
export { ICustomPluginFactory__factory } from "./ICustomPluginFactory__factory";
